name             'orchestrator'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chef-orchestrator'
long_description 'Installs/Configures chef-orchestrator'
version          '0.1.0'

depends 'yum'
depends 'database'
depends 'percona'
